baseURL = "http://essenceia/github.io/darwinlabs"
languagecode = "en"
title = "Site de raph"
theme = "coder-portfolio"

defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without
pygmentsUseClasses = true # new add
staticDir = "static"
publishDir= "docs"
[params] # theme parameters
    author = "Raphael Outhier" # Author's name.
    info = "EMBEDDED AND SYSTEM DEVELOPER" # Author's job title or info.
    description = "Rapheal Ouhier's personal website" # Site description.
    keywords = "blog,developer,personal,C,embedded,tracer,microkernel" # Site keywords.
    avatarurl = "images/profile.jpg" # Contain the path of the optionnal avatar in the
    thummbnail = "images/icon.png"
    footercontent = "Enter a text here." # Add footer content
    fixedbarContent = "Want to know more about me ?→" # Add fixedbar
    fixedbarContentAfter = "" # Add
    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    snsShare = false  # new add

    thumbnail = "images/profile.jpg" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is 

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/Briztal/"
[[params.social]]
    name = "LinkedIn"
    weight = 2
    url = "https://www.linkedin.com/in/rapha%C3%ABl-outhier-882661165/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "blog"
[[menu.main]]
    name = "Projects"
    weight = 2
    url  = "projects"
[[menu.main]]
    name = "About"
    weight = 3
    url = "about"


